// LOCAL
### Get all contacts
GET http://localhost:3080/contacts

### Get contact by ID
GET http://localhost:3080/contacts/000000000000000000000001

### Create contact
POST http://localhost:3080/contacts
Content-Type: application/json

{
  "firstName": "Jared",
  "lastName": "Samayoa",
  "email": "jared@blink182.com",
  "favoriteColor": "black",
  "birthday": "04/04/2004"
}

### Update contact
PUT http://localhost:3080/contacts/69bedef880a2b20ac9858060
Content-Type: application/json

{
  "firstName": "Jared",
  "lastName": "Samayoa",
  "email": "jared@blink182.com",
  "favoriteColor": "black",
  "birthday": "04/04/2000"
}

### Delete contact
DELETE http://localhost:3080/contacts/69bedef880a2b20ac9858060



// PROD
### Get all contacts
GET https://js-cse341-project1.onrender.com/contacts

### Get contact by ID
GET https://js-cse341-project1.onrender.com/contacts/000000000000000000000001

### Create contact
POST http://localhost:3080/contacts
Content-Type: application/json

{
  "firstName": "Jared",
  "lastName": "Samayoa",
  "email": "jared@blink182.com",
  "favoriteColor": "black",
  "birthday": "04/04/2004"
}

### Update contact
PUT https://js-cse341-project1.onrender.com/contacts/69bedef880a2b20ac9858060
Content-Type: application/json

{
  "firstName": "Jared",
  "lastName": "Samayoa",
  "email": "jared@blink182.com",
  "favoriteColor": "black",
  "birthday": "04/04/2000"
}

### Delete contact
DELETE https://js-cse341-project1.onrender.com/contacts/69bedef880a2b20ac9858060